apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  eureka-url: http://discovery-server:8761/eureka
  config-url: optional:configserver:http://config-server:8888
  kafka-url: kafka:9092
  users-db-url: jdbc:postgresql://postgres-users:5432/users_db
  shipments-db-url: jdbc:postgresql://postgres-shipments:5432/shipments_db
  deliveries-db-url: jdbc:postgresql://postgres-deliveries:5432/deliveries_db
  notifications-db-url: jdbc:postgresql://postgres-notifications:5432/notifications_db
  mongo-url: mongodb://mongo:mongo@mongo-tracking:27017/tracking_db?authSource=admin
  zipkin-url: http://zipkin:9411/api/v2/spans
