apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delivery-tracking-ingress
spec:
  rules:
    - host: delivery-tracking.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
