apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-tracking

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - databases.yaml
  - kafka.yaml
  - zipkin.yaml
  - apps.yaml
  - gateway-ingress.yaml
